services:
  db:
    image: postgres:16
    env_file: ".env"
    container_name: db
    volumes:
      - "db_data:/var/lib/postgresql/data"
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10


  django:
    command: sh -c "python manage.py makemigrations && python manage.py migrate --noinput && pytest && python manage.py runserver 0.0.0.0:8000"
    build: .
    container_name: "django"
    ports:
      - "8000:8000"
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy


volumes:
  db_data:
